export { scss } from "./scss.js"
export { index, page404 } from "./html.js"
export { optimg } from "./optimg.js"
export { eslint } from "./eslint.js"
export { hotReload } from "./hot.js"
export { cleaner } from "./cleaner.js"
export { favicon } from "./favicon.js"
